# Generated by Django 2.1.7 on 2019-03-30 16:00

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RosbagInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_name', models.TextField()),
                ('bag_size', models.FloatField()),
                ('content_topics', django_mysql.models.ListTextField(models.CharField(max_length=30), size=None)),
                ('content_types', django_mysql.models.ListTextField(models.CharField(max_length=30), size=None)),
                ('content_msgnum', django_mysql.models.ListTextField(models.CharField(max_length=30), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RosbagParsedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
